/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_logicsquare_GameActivity */

#ifndef _Included_com_example_logicsquare_GameActivity
#define _Included_com_example_logicsquare_GameActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_logicsquare_GameActivity
 * Method:    printDot
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_logicsquare_GameActivity_printDot
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_logicsquare_GameActivity
 * Method:    printFnd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_logicsquare_GameActivity_printFnd
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
