/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_logicsquare_EndActivity */

#ifndef _Included_com_example_logicsquare_EndActivity
#define _Included_com_example_logicsquare_EndActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_logicsquare_EndActivity
 * Method:    nowScore
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_logicsquare_EndActivity_nowScore
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
